language: python
services:
  - redis-server
  - mongodb
  - rabbitmq
before_install:
  - sudo apt-get -q update
  - sudo apt-get -q build-dep python-scipy
  - sudo apt-get install -qq python-scipy
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r test-requirements.txt --use-mirrors
  - pip install -q $DJANGO
  - pip install -q $CELERY
  - pip install -q $DJCELERY
before_script:
  - "export PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH;"
  - "django-admin.py version;"
  - "flake8 --exclude=migrations --ignore=E501,E123,E124,E126,E127,E128 --statistics .;"
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - DJANGO="Django>=1.4,<1.5",CELERY="celery>=2.0,<3.0",DJCELERY="django-celery>=2.0,<3.0"
  - DJANGO="Django>=1.5,<1.6",CELERY="celery>=2.0,<3.0",DJCELERY="django-celery>=2.0,<3.0"
  - DJANGO="Django>=1.6,<1.7",CELERY="celery>=2.0,<3.0",DJCELERY="django-celery>=2.0,<3.0"
  - DJANGO="Django>=1.4,<1.5",CELERY="celery>=3.0,<4.0",DJCELERY="django-celery>=3.0,<4.0"
  - DJANGO="Django>=1.5,<1.6",CELERY="celery>=3.0,<4.0",DJCELERY="django-celery>=3.0,<4.0"
  - DJANGO="Django>=1.6,<1.7",CELERY="celery>=3.0,<4.0",DJCELERY="django-celery>=3.0,<4.0"
script: python recommends/tests/runtests.py
after_failure:
  - env
  - cat $PYTHONPATH
